image:
  repository: ghcr.io/mindtastic/bouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "66196ce951b02719a1610f3ba55e5fc3a2710c06"

podCommand: 
- "/bouncer"
- "-downstream=http://kratos-public.kratos.svc.cluster.local"

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: allowCORS@file
  hosts:
    - host: auth.api.live.mindtastic.lol
      paths:
        - path: /self-service/registration
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

