image:
  repository: ghcr.io/mindtastic/bouncer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "66196ce951b02719a1610f3ba55e5fc3a2710c06"

podCommand: 
- "/bouncer"
- "-downstream=http://kratos-public.kratos.svc.cluster.local"
- "-log=true"

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: auth.api.dev.mindtastic.lol
      paths:
        - path: /self-service/registration
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

