apiVersion: v2
name: community-operator
description: MongoDB Kubernetes Community Operator
version: 0.7.3
type: application
appVersion: 0.7.3
kubeVersion: '>=1.16-0'
keywords:
- mongodb
- database
- nosql
icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
