image:
  repository: ghcr.io/mindtastic/wiki-service
  pullPolicy: IfNotPresent
  tag: "a1b04fdf126bbaa7a8fbc49af56319a599c7bd3c"

accessRule:
  matchPath: "https://wiki.api.live.mindtastic.lol/wiki"
  matchMethods: ["GET"]
  kratosCheckSessionURL: http://kratos-public.kratos.svc.cluster.local/sessions/whoami
  kodaHydratorURL: http://koda.koda.svc.cluster.local:4133/

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth@file
  hosts:
    - host: "wiki.api.live.mindtastic.lol"
      paths:
        - path: /
          pathType: Prefix
  tls: []