apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouncer-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: bouncer
    helm:
      releaseName: bouncer
      valueFiles:
      - values-dev.yaml    
  destination:
    server: https://cluster.net.dev.mindtastic.lol
    namespace: bouncer # Namespace for your application
