apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bouncer-live
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: bouncer
    helm:
      releaseName: bouncer
      valueFiles:
      - values-live.yaml    
  destination:
    server: "https://kubernetes.default.svc"
    namespace: bouncer # Namespace for your application
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
