apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-live
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: keycloak
    helm:
      releaseName: keycloak
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
