apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koda-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: koda
    helm:
      releaseName: koda
      valueFiles:
      - values-common.yaml
      - values-dev.yaml      
  destination:
    server: "https://cluster.net.dev.mindtastic.lol"
    namespace: koda
  syncPolicy:
      syncOptions:
        - CreateNamespace=true