apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koda-live
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: koda
    helm:
      releaseName: koda
      valueFiles:
      - values-live.yaml      
  destination:
    server: "https://kubernetes.default.svc"
    namespace: koda
  syncPolicy:
      syncOptions:
        - CreateNamespace=true