apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratos-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: kratos
    helm:
      releaseName: kratos
      valueFiles:
      - values-dev.yaml      
  destination:
    server: "https://cluster.net.dev.mindtastic.lol"
    namespace: kratos
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
