apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack-dev   
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: kube-prometheus-stack 
    helm:
      releaseName: kube-prometheus-stack
      valueFiles:
      - values-common.yaml
      - values-dev.yaml 
  destination:
    server: https://cluster.net.dev.mindtastic.lol
    namespace: monitoring 
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - Replace=true
