apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-operator-dev   
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: mongodb-operator 
    helm:
      releaseName: mongodb-operator
      valueFiles:
      - values-common.yaml
      - values-dev.yaml 
  destination:
    server: https://cluster.net.dev.mindtastic.lol
    namespace: mongodb 
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
