apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mood-diary-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: mood-diary
    helm:
      releaseName: mood-diary
      valueFiles:
      - values-common.yaml
      - values-dev.yaml    
  destination:
    server: https://cluster.net.dev.mindtastic.lol
    namespace: mood-diary # Namespace for your application
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
