apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: motivator-service-live
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: motivator-service
    helm:
      releaseName: motivator-service
      valueFiles:
      - values-common.yaml
      - values-live.yaml    
  destination:
    server: https://kubernetes.default.svc
    namespace: motivator-service # Namespace for your application
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
