apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oathkeeper-live
  namespace: argocd
spec:
  project: default
  source:
    chart: oathkeeper
    repoURL: https://k8s.ory.sh/helm/charts
    targetRevision: 0.23.2
    path: oathkeeper
    helm:
      releaseName: oathkeeper
      valueFiles:
      - values-live.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: oathkeeper
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
