apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oathkeeper-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: oathkeeper
    helm:
      releaseName: oathkeeper
      valueFiles:
      - values-dev.yaml
  destination:
    server: "https://cluster.net.dev.mindtastic.lol"
    namespace: oathkeeper
  syncPolicy:
      syncOptions:
        - CreateNamespace=true
