apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: traefik
    helm:
      releaseName: traefik
      valueFiles:
      - values-dev.yaml
  destination:
    server: "https://cluster.net.dev.mindtastic.lol"
    namespace: traefik
  syncPolicy:
    syncOptions:
      - CreateNamespace=true