apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mindtastic/deployments
    targetRevision: HEAD
    path: user-service
    helm:
      releaseName: user-service
      valueFiles:
      - values-dev.yaml    
  destination:
    server: https://cluster.net.dev.mindtastic.lol
    namespace: user-service # Namespace for your application
