image:
  repository: ghcr.io/mindtastic/motivator-service
  pullPolicy: IfNotPresent
  tag: "c86344834ae5d448f6cacce622afccf2bc2eeb24"

accessRule:
  unauthenticated: true
  matchPath: "https://motivator.api.dev.mindtastic.lol/<.+>"
  matchMethods: ["POST", "GET", "PUT", "DELETE"]
  kratosCheckSessionURL: http://kratos-public.kratos.svc.cluster.local/sessions/whoami
  kodaHydratorURL: http://koda.koda.svc.cluster.local:4133/

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth@file
  hosts:
    - host: "motivator.api.dev.mindtastic.lol"
      paths:
        - path: /
          pathType: Prefix
  tls: []
