apiVersion: v1
kind: Namespace
metadata:
  name: tilt

---
apiVersion: v1
kind: Service
metadata:
  name: kagami-tilt
  namespace: tilt
spec:
  type: ExternalName
  externalName: kagami.kagami.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-tilt
  namespace: tilt
spec:
  type: ExternalName
  externalName: user-service.user-service.svc.cluster.local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kagami
  namespace: tilt
  labels:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: allowInternalIPs@file
spec:
  ingressClassName: traefik
  rules:
    - host: "tilt.api.dev.mindtastic.lol"
      http:
        paths:
          - path: echo.api.dev.mindtastic.lol/
            pathType: Prefix
            backend:
              service:
                name: kagami-tilt
                port:
                  name: http