ingress:
  public:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: traefik
      #kubernetes.io/tls-acme: "true"
    hosts:
      - host: auth.api.live.mindtastic.lol
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

kratos:
  development: false
  config:
    serve:
      public:
        port: 4433
        base_url: "https://auth.api.live.mindtastic.lol"
      admin:
        port: 4434

    selfservice:
      default_browser_return_url: https://auth-example.api.live.mindtastic.lol/

      flows:
        registration:
          lifespan: 15m
          ui_url: https://auth-example.api.live.mindtastic.lol/registration
          after:
            password:
              hooks:
                - hook: session

        login:
          lifespan: 15m
          ui_url: https://auth-example.api.dev.mindtastic.lol/login
        error:
          ui_url: https://auth-example.api.live.mindtastic.lol/error
        logout:
          after:
            default_browser_return_url: https://auth-example.api.live.mindtastic.lol
