image:
  repository: ghcr.io/mindtastic/mood-diary
  pullPolicy: IfNotPresent
  tag: "fae23712916ded632e6bed2ced346d2266e94293"

accessRule:
  unauthenticated: true
  matchPath: "https://mood.api.dev.mindtastic.lol/diary"
  matchMethods: ["POST", "GET", "PUT", "DELETE"]
  kratosCheckSessionURL: http://kratos-public.kratos.svc.cluster.local/sessions/whoami
  kodaHydratorURL: http://koda.koda.svc.cluster.local:4133/

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth@file
  hosts:
    - host: "mood.api.dev.mindtastic.lol"
      paths:
        - path: /
          pathType: Prefix
  tls: []
