apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: auth@file

spec:
  ports:
    - protocol: TCP
      name: web
      port: 8000
  selector:
    app: user-service